services:
  server:
    build:
      context: .
      target: final
    ports:
      - 3000:3000
    environment:
      - PG_DBNAME=rustwebdev
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORDFILE=/run/secrets/db-password
    secrets:
      - db-password
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rustwebdev
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
